version: '3.9'

# 这里定义了公用的环境变量，方便下面复用
x-kong-env: &kong-env
  KONG_DATABASE: postgres
  KONG_PG_HOST: kong-db
  KONG_PG_USER: kong
  KONG_PG_PASSWORD: kongpass
  KONG_PROXY_ACCESS_LOG: /dev/stdout
  KONG_ADMIN_ACCESS_LOG: /dev/stdout
  KONG_PROXY_ERROR_LOG: /dev/stderr
  KONG_ADMIN_ERROR_LOG: /dev/stderr
  KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
  KONG_LUA_SHARED_DICTS: blacklist_cache 5m, locks_cache 1m
  # 注意这一行：将来我们写好插件，就要把名字加在这里告诉 Kong 去加载它
  KONG_PLUGINS: bundled,pomodoro-plugin

services:

  # 1. 新增 Redis 容器
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
      
  # 1. 数据库节点
  kong-db:
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. 数据库初始化任务 (仅在第一次启动时建表，跑完就退出)
  kong-migrations:
    image: kong:latest
    environment:
      <<: *kong-env
    command: kong migrations bootstrap
    depends_on:
      kong-db:
        condition: service_healthy
        

  # 3. Kong 核心网关节点
  kong:
    image: kong:latest
    environment:
      <<: *kong-env
    depends_on:
      redis:
        condition: service_started
      kong-migrations:
        condition: service_completed_successfully
    ports:
      # 代理端口：用户的真实请求打到这里
      - "8000:8000"
      - "8443:8443"
      # 管理端口：你用来配置路由、挂载插件的后门 API
      - "8001:8001"
      - "8444:8444"
    # 下面这两行极其重要，我们下一步写代码时，要把本地的代码映射到容器里去
    volumes:
     - ./pomodoro-plugin:/usr/local/share/lua/5.1/kong/plugins/pomodoro-plugin